# Numpy practice session

In [1]:
import numpy as np

## Creating an array using numpy

In [2]:
product = np.array(["Shirt", "pent", "kurta"])  # the last digits in arrays or python is actually exclusive
product

array(['Shirt', 'pent', 'kurta'], dtype='<U5')

In [3]:
price = np.array([500, 1500, 2500])
price

array([ 500, 1500, 2500])

In [4]:
type(product)

numpy.ndarray

In [5]:
type(price)

numpy.ndarray

In [6]:
len(product)

3

In [7]:
len(price)

3

In [8]:
product[2]  #indexing

'kurta'

In [9]:
product[:2]

array(['Shirt', 'pent'], dtype='<U5')

In [10]:
price.mean()

1500.0

In [11]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [12]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.empty(5)

array([2.22526399e-307, 6.23053614e-307, 7.56592338e-307, 9.34588061e-307,
       4.45014772e-307])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
a = np.arange(5005)
a

array([   0,    1,    2, ..., 5002, 5003, 5004])

In [16]:
#  Specify
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [17]:
# specific
np.arange(1, 20, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [18]:
# table of 5
np.arange(5, 55, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [19]:
# line space
np.linspace(1, 10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [20]:
np.linspace(1, 50, num=10)

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [21]:
# specify your data type
np.ones(20, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      dtype=int64)

In [22]:
np.ones(10, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Array Function

In [23]:
a = np.array([15, 5, 7, 3, 10.5, 100, 60, 40,25])
a

array([ 15. ,   5. ,   7. ,   3. ,  10.5, 100. ,  60. ,  40. ,  25. ])

In [24]:
a.sort()
a

array([  3. ,   5. ,   7. ,  10.5,  15. ,  25. ,  40. ,  60. , 100. ])

In [25]:
b = np.array([25, 15, 10, 6, 3, 100, 67, 56, 34, 20])
b

array([ 25,  15,  10,   6,   3, 100,  67,  56,  34,  20])

In [26]:
b.sort()
b

array([  3,   6,  10,  15,  20,  25,  34,  56,  67, 100])

In [27]:
# concatenate
c = np.concatenate((a,b))
c

array([  3. ,   5. ,   7. ,  10.5,  15. ,  25. ,  40. ,  60. , 100. ,
         3. ,   6. ,  10. ,  15. ,  20. ,  25. ,  34. ,  56. ,  67. ,
       100. ])

In [28]:
c.sort()
c

array([  3. ,   3. ,   5. ,   6. ,   7. ,  10. ,  10.5,  15. ,  15. ,
        20. ,  25. ,  25. ,  34. ,  40. ,  56. ,  60. ,  67. , 100. ,
       100. ])

## 2 Dimentional array

In [29]:
a = np.array([[1, 2, 3, 4,],[5, 6, 7, 8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
b = np.array([[9, 10, 11,12]])
b

array([[ 9, 10, 11, 12]])

In [31]:
np.concatenate((a,b), axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
x= np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [33]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [34]:
np.concatenate((x,y), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [35]:
a = np.array([[[0,1,2,3],
                 [4,5,6,7]],
          
                 [[0,1,2,3],       
                  [4,5,6,7]],
          
                 [[0,1,2,3],
                  [4,5,6,7]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [36]:
a.ndim

3

In [37]:
b = np.array([[5,6,7],
              [8,9,10],
              [11, 12,13]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [38]:
b.ndim

2

In [39]:
a.size

24

In [40]:
a.shape

(3, 2, 4)

In [41]:
b.size

9

In [42]:
b.shape

(3, 3)

In [43]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [44]:
b = a.reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [45]:
c = np.arange(9)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
c.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
# reshape
np.reshape(c, newshape=(1, 9), order='C' )

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [53]:
# Convert 1D into 2D
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
a.shape 

(9,)

In [55]:
# rowwise 2D conversion
b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [56]:
b.shape

(1, 9)

In [57]:
# column wise 2D conversion
c = a[:, np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [59]:
# array can be taken in repetition
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
# repetition
a*5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [61]:
a+5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [66]:
a/2 

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [68]:
a-2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7])

In [69]:
a.sum()

45

In [70]:
a.mean()

5.0